# push_to_github_fixed.ps1
# PowerShell v5.1-compatible helper to commit & push local changes to GitHub.
# Usage:
#   Set-Location -Path 'D:\Durgesh\wise-global\wise-global'
#   .\push_to_github_fixed.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($PSScriptRoot) { Set-Location $PSScriptRoot }
Write-Host "Working directory: $(Get-Location)" -ForegroundColor Cyan

function Run-Git {
    param([Parameter(Mandatory=$true)] [string[]] $Args)
    & git @Args
    return $LASTEXITCODE
}

# Check git availability
try {
    Run-Git --version > $null 2>&1
    if ($LASTEXITCODE -ne 0) { throw "git not available" }
} catch {
    Write-Error "Git is not installed or not in PATH. Please install Git for Windows: https://git-scm.com/download/win"
    exit 1
}

# Initialize repo if missing
if (-not (Test-Path .git)) {
    Write-Host ".git directory not found. Initializing a new git repository..." -ForegroundColor Yellow
    Run-Git init
    if ($LASTEXITCODE -ne 0) { Write-Error "git init failed"; exit 1 }
}

# Ensure server/.env is ignored
$gitignorePath = ".gitignore"
$entry = "server/.env"
if (-not (Test-Path $gitignorePath)) {
    "# Auto-generated by push_to_github_fixed.ps1`n$entry" | Out-File -FilePath $gitignorePath -Encoding utf8
    Write-Host "Created .gitignore and added server/.env" -ForegroundColor Green
} else {
    $gitignore = Get-Content $gitignorePath -Raw
    if ($gitignore -notmatch [regex]::Escape($entry)) {
        Add-Content -Path $gitignorePath -Value "`n$entry"
        Write-Host "Appended server/.env to .gitignore" -ForegroundColor Green
    } else {
        Write-Host "server/.env already listed in .gitignore" -ForegroundColor DarkYellow
    }
}

# Remove server/.env from index if tracked
Run-Git ls-files --error-unmatch server/.env > $null 2>&1
$isTracked = $LASTEXITCODE -eq 0
if ($isTracked) {
    Write-Host "server/.env is tracked in git index — removing from index (won't delete file)" -ForegroundColor Yellow
    Run-Git rm --cached server/.env -q
    if ($LASTEXITCODE -ne 0) { Write-Host "git rm failed or server/.env not in index" -ForegroundColor Yellow }
} else {
    Write-Host "server/.env not tracked — good." -ForegroundColor Green
}

# Show current branch
$branch = (Run-Git rev-parse --abbrev-ref HEAD 2>$null | Out-String).Trim()
if (-not $branch -or $branch -eq 'HEAD') {
    $branch = Read-Host "Unable to detect current branch name; enter the branch name to use (suggest 'main')"
    if (-not $branch) { $branch = 'main' }
}
Write-Host "Current branch: $branch"

# Stage files and commit
Write-Host "Staging all changes..." -ForegroundColor Cyan
Run-Git add -A

$commitMessage = "Initial commit from local workspace"
Run-Git commit -m $commitMessage -q
if ($LASTEXITCODE -eq 0) {
    Write-Host "Committed changes: $commitMessage" -ForegroundColor Green
} else {
    Write-Host "No changes to commit (or commit failed). Continuing..." -ForegroundColor Yellow
}

# Setup remote if not present
$defaultRemote = 'https://github.com/Durgesh122/Wise_globle_research.git'
$remotesOutput = (Run-Git remote) | Out-String
if (-not $remotesOutput.Trim()) {
    Write-Host "No remote configured. Adding origin -> $defaultRemote" -ForegroundColor Cyan
    Run-Git remote add origin $defaultRemote
    if ($LASTEXITCODE -ne 0) { Write-Error "Failed to add remote origin"; exit 1 }
} else {
    Write-Host "Existing remotes:" -ForegroundColor Cyan
    Run-Git remote -v
}

# Push
Write-Host "Pushing branch $branch to origin..." -ForegroundColor Cyan
Run-Git push -u origin $branch
if ($LASTEXITCODE -eq 0) {
    Write-Host "Push succeeded." -ForegroundColor Green
} else {
    Write-Error "Push failed. You may need to authenticate (use PAT or SSH) or create the remote branch on GitHub. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token for PAT info."
    exit 1
}

Write-Host "Done. If push failed due to authentication, try configuring SSH keys or use a Personal Access Token for HTTPS." -ForegroundColor Cyan
