# push_to_github.ps1
# Safe helper to commit & push local changes to GitHub from Windows PowerShell.
# It ensures server/.env is ignored and removed from the index before committing.
# Usage: Right-click -> "Run with PowerShell" in the project folder, or run from PowerShell:
#   cd D:\Durgesh\wise-global\wise-global
#   .\push_to_github.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Move to script directory (assumes script is in repo root)
if ($PSScriptRoot) { Set-Location $PSScriptRoot }

Write-Host "Working directory: $(Get-Location)" -ForegroundColor Cyan

# Check git availability
try {
    git --version > $null 2>&1
} catch {
    Write-Error "Git is not installed or not in PATH. Please install Git for Windows: https://git-scm.com/download/win"
    exit 1
}

# Confirm we're in a git repo
if (-not (Test-Path .git)) {
    Write-Host ".git directory not found. Initializing a new git repository..." -ForegroundColor Yellow
    git init
}

# Ensure server/.env is ignored
$gitignorePath = ".gitignore"
$entry = "server/.env"
if (-not (Test-Path $gitignorePath)) {
    "# Auto-generated by push_to_github.ps1`n$entry" | Out-File -FilePath $gitignorePath -Encoding utf8
    Write-Host "Created .gitignore and added server/.env" -ForegroundColor Green
} else {
    $gitignore = Get-Content $gitignorePath -Raw
    if ($gitignore -notmatch [regex]::Escape($entry)) {
        Add-Content -Path $gitignorePath -Value "`n$entry"
        Write-Host "Appended server/.env to .gitignore" -ForegroundColor Green
    } else {
        Write-Host "server/.env already listed in .gitignore" -ForegroundColor DarkYellow
    }
}

# Remove server/.env from index if tracked
try {
    git ls-files --error-unmatch server/.env > $null 2>&1
    $isTracked = $LASTEXITCODE -eq 0
} catch {
    $isTracked = $false
}
if ($isTracked) {
    Write-Host "server/.env is tracked in git index — removing from index (won't delete file)" -ForegroundColor Yellow
    git rm --cached server/.env -q || Write-Host "git rm failed or server/.env not in index" -ForegroundColor Yellow
} else {
    Write-Host "server/.env not tracked — good." -ForegroundColor Green
}

# Show current branch
$branch = git rev-parse --abbrev-ref HEAD 2>$null
if (-not $branch -or $branch -eq 'HEAD') {
    $branch = Read-Host "Unable to detect current branch name; enter the branch name to use (suggest 'main')"
    if (-not $branch) { $branch = 'main' }
}
Write-Host "Current branch: $branch"

# Stage files and commit
Write-Host "Staging all changes..." -ForegroundColor Cyan
git add -A

$commitMessage = "Leedsfrom: non-blocking submit; include hemraj recipient; avoid central mailbox for Leedsfrom. Add AMP page."
try {
    git commit -m "$commitMessage" -q
    Write-Host "Committed changes: $commitMessage" -ForegroundColor Green
} catch {
    Write-Host "No changes to commit (or commit failed). Continuing..." -ForegroundColor Yellow
}

# Setup remote if not present
$defaultRemote = 'https://github.com/Durgesh122/Wise_globle_research.git'
$remotes = git remote
if (-not $remotes) {
    Write-Host "No remote configured. Adding origin -> $defaultRemote" -ForegroundColor Cyan
    git remote add origin $defaultRemote
} else {
    Write-Host "Existing remotes:" -ForegroundColor Cyan
    git remote -v
}

# Push
Write-Host "Pushing branch $branch to origin..." -ForegroundColor Cyan
try {
    git push -u origin $branch
    Write-Host "Push succeeded." -ForegroundColor Green
} catch {
    Write-Error "Push failed. You may need to authenticate (use PAT or SSH) or create the remote branch on GitHub. Error: $_"
    exit 1
}

Write-Host "Done. If push failed due to authentication, try configuring SSH keys or use a Personal Access Token for HTTPS." -ForegroundColor Cyan

# End
