// Simple KB generator: reads site pages and docs and writes src/data/chatKB.auto.js
// Usage: node scripts/generate-kb.js
const fs = require('fs');
const path = require('path');

const workspace = path.resolve(__dirname, '..');
const srcPages = path.join(workspace, 'src', 'pages');
const publicDir = path.join(workspace, 'public');
const docsDir = path.join(workspace, 'Documentation');
const outFile = path.join(workspace, 'src', 'data', 'chatKB.auto.js');

function safeRead(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (e) {
    return null;
  }
}

function extractFromJSX(content) {
  // try to find <title>...</title>
  const titleMatch = content.match(/<title>([^<]+)<\//i);
  const metaMatch = content.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i);
  const h1 = content.match(/<h1[^>]*>([^<]+)<\//i);
  const p = content.match(/<p[^>]*>([^<]{30,300})<\//i);
  return {
    title: titleMatch ? titleMatch[1].trim() : (h1 ? h1[1].trim() : null),
    description: metaMatch ? metaMatch[1].trim() : (p ? p[1].trim() : null),
  };
}

function extractFromHTML(content) {
  const title = content.match(/<title>([^<]+)<\//i);
  const meta = content.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i);
  const h1 = content.match(/<h1[^>]*>([^<]+)<\//i);
  const p = content.match(/<p[^>]*>([^<]{30,300})<\//i);
  return {
    title: title ? title[1].trim() : (h1 ? h1[1].trim() : null),
    description: meta ? meta[1].trim() : (p ? p[1].trim() : null),
  };
}

function extractFromMD(content) {
  const title = content.match(/^#\s+(.+)$/m);
  const para = content.match(/(?:^|\n)([^\n][^\n]{30,400})/);
  return { title: title ? title[1].trim() : null, description: para ? para[1].trim().replace(/\n/g, ' ') : null };
}

const entries = [];

// scan src/pages
if (fs.existsSync(srcPages)) {
  const files = fs.readdirSync(srcPages).filter(f => f.endsWith('.js') || f.endsWith('.jsx'));
  for (const f of files) {
    const full = path.join(srcPages, f);
    const content = safeRead(full);
    if (!content) continue;
    const { title, description } = extractFromJSX(content);
    const id = `page_${path.basename(f, path.extname(f))}`;
    const keywords = [];
    if (title) keywords.push(...title.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,6));
    if (description) keywords.push(...description.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,6));
    if (title || description) {
      entries.push({ id, title: title || id, keywords: Array.from(new Set(keywords)).slice(0,10), answer: description || `Information about ${title || id}.` });
    }
  }
}

// scan public html files (index, temp_home)
if (fs.existsSync(publicDir)) {
  const files = fs.readdirSync(publicDir).filter(f => f.endsWith('.html'));
  for (const f of files) {
    const full = path.join(publicDir, f);
    const content = safeRead(full);
    if (!content) continue;
    const { title, description } = extractFromHTML(content);
    const id = `public_${path.basename(f, path.extname(f))}`;
    const keywords = [];
    if (title) keywords.push(...title.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,6));
    if (description) keywords.push(...description.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,6));
    if (title || description) {
      entries.push({ id, title: title || id, keywords: Array.from(new Set(keywords)).slice(0,10), answer: description || `Information about ${title || id}.` });
    }
  }
}

// scan Documentation md files
if (fs.existsSync(docsDir)) {
  const files = fs.readdirSync(docsDir).filter(f => f.endsWith('.md'));
  for (const f of files) {
    const full = path.join(docsDir, f);
    const content = safeRead(full);
    if (!content) continue;
    const { title, description } = extractFromMD(content);
    const id = `doc_${path.basename(f, path.extname(f))}`;
    const keywords = [];
    if (title) keywords.push(...title.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,8));
    if (description) keywords.push(...description.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).slice(0,8));
    if (title || description) {
      entries.push({ id, title: title || id, keywords: Array.from(new Set(keywords)).slice(0,12), answer: description || `Documentation: ${title || id}.` });
    }
  }
}

// Deduplicate by id
const uniq = [];
const seen = new Set();
for (const e of entries) {
  if (seen.has(e.id)) continue;
  seen.add(e.id);
  uniq.push(e);
}

// write out file
const out = `// AUTO-GENERATED KB: do not edit by hand. Generated by scripts/generate-kb.js
// Contains simple Q/A entries derived from project pages and documentation.

const AUTO_KB = ${JSON.stringify(uniq, null, 2)};

export default AUTO_KB;
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out, 'utf8');
console.log('Wrote', outFile, 'with', uniq.length, 'entries');
